services:
  web:
    build: .
    ports:
      - "${API_PORT}:8000"
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}